import type { CollectionConfig } from 'payload'

import { publishedOnly } from '../access/publishedOnly'
import { authenticated } from '../access/authenticated'

/**
 * ActivityEvents — GitHub-synced events (Phase 2 upserts by externalId). One of
 * the three sources unioned into the Activity feed. Editorial flags (published/
 * pinned/authorship) are preserved across syncs.
 */
export const ActivityEvents: CollectionConfig = {
  slug: 'activity-events',
  labels: { singular: 'Activity Event', plural: 'Activity Events' },
  access: { create: authenticated, delete: authenticated, read: publishedOnly, update: authenticated },
  admin: { useAsTitle: 'title', group: 'Activity', defaultColumns: ['title', 'kind', 'occurredAt', 'published'] },
  fields: [
    // ---- GitHub-synced — read-only in the CMS (the sync writes via the API) ----
    { name: 'title', type: 'text', required: true, admin: { readOnly: true } },
    {
      name: 'kind',
      type: 'select',
      defaultValue: 'commit',
      admin: { readOnly: true },
      options: [
        { label: 'Commits', value: 'commit' },
        { label: 'Release', value: 'release' },
        { label: 'New repo', value: 'repo' },
        { label: 'Pull request', value: 'pr' },
      ],
    },
    { name: 'repoFullName', type: 'text', label: 'Repo (owner/repo)', admin: { readOnly: true } },
    { name: 'url', type: 'text', admin: { readOnly: true } },
    { name: 'occurredAt', type: 'date', required: true, admin: { readOnly: true } },
    { name: 'additions', type: 'number', admin: { readOnly: true } },
    { name: 'deletions', type: 'number', admin: { readOnly: true } },
    { name: 'externalId', type: 'text', unique: true, admin: { position: 'sidebar', readOnly: true, description: 'Sync dedupe key.' } },
    {
      name: 'actor',
      type: 'text',
      label: 'GitHub actor',
      admin: { position: 'sidebar', readOnly: true, description: 'GitHub username(s) behind this event, from the sync.' },
    },
    // Sync SEEDS this (human, or human-AI when an AI co-author trailer is found),
    // but it is editable — the sync only fills it when empty, so corrections stick.
    {
      name: 'authorship',
      type: 'select',
      admin: { position: 'sidebar', description: 'Who did the work. Sync seeds it; edit to correct.' },
      options: [
        { label: '● Human', value: 'human' },
        { label: '◐ Human + AI', value: 'human-ai' },
        { label: '◑ AI', value: 'ai' },
      ],
    },
    // ---- Editable in the CMS ----
    { name: 'project', type: 'relationship', relationTo: 'projects' },
    {
      name: 'summary',
      type: 'textarea',
      label: 'Summary (AI-generated)',
      admin: {
        description:
          'A 2–3 line plain-language summary of what this commit/PR did, generated by the sync (Gemini) from the commit messages / PR body. Shown in the activity feed. Edit freely — the sync fills it once and never overwrites your edits.',
      },
    },
    {
      name: 'note',
      type: 'textarea',
      label: 'Note (manual)',
      admin: { description: 'Optional manual annotation — shown under the summary in the activity feed.' },
    },
    { name: 'published', type: 'checkbox', defaultValue: false, admin: { position: 'sidebar' } },
    { name: 'pinned', type: 'checkbox', defaultValue: false, admin: { position: 'sidebar' } },
  ],
}
